### PR TITLE
Changes in PC configuration section header

### PR DESCRIPTION
**Pull request by bamh**
*Fixed: https://issues.jenkins-ci.org/browse/JENKINS-39654
*Changes in PC configuration section header

### CODE REVIEW

**Comment by YafimK** [comment]
- [ ] Please add proper description.
- [ ] Please add Jira Ticket.

**Comment by YafimK** [comment]
Approved for test build

**Comment by YafimK** [comment]
Ignore AppVeyor

**Comment by bamh** [comment]
Added the Jira Ticket and description

**Comment by bamh** [comment]
Ignore codacy message - these are for future changes

**Comment by YafimK** [comment]
Please fix conflicts wither here or by rebasing.

**Pull request closed without merging**
