### PR TITLE
Sending logs with Apache client & Removed dependency in Bdi SDK

### PR DESCRIPTION
**Pull request by orenbm21**
1. Fixed the log sending as we now work with Apache client instead of Jersey.
2. For now, the Apache client sits inside the plugin until the Bdi SDK is stabled. Until then, there's no need in a dependency in the sdk.

### CODE REVIEW

**Comment by YafimK** [comment]
approved for test build

**Comment by YafimK** [comment]
Seems to fail due to files from previous commit, which was not merged on this branch - "fixing uft test detection (commit: 3ab19f0)".
Please investigate.
@m-seldin

**Comment by YafimK** [comment]
approved for test build

**Comment by m-seldin** [comment]
approved for test build

**Pull request closed without merging**
