### PR TITLE
Uft test discovery and execution

### PR DESCRIPTION
**Pull request by radislavB**
**1.Test discovery changes**
a. New fields that are populated during test discovered : 
- test description
- test type (API or GUI)
- scm repository

b. Activating discovery on changeSet and updating test description (if changed)
c. Support persistence of discovery results (to handle octane disconnections)

**2.Test execution changes** : job that created for test execution , contains (as parameter) suite id and execution id. It will be used later for enrichments test results in Octane

**3.Run UFT tests from file system** : added possibility to insert  MTBX file content as a parameter.
(Previously, it was possible to set reference to MTBX file)

**4.Purging of jobs** : Adding support for purging of outdated jobs , that were created for uft discovery and execution

### CODE REVIEW

**Comment by m-seldin** [comment]
approved for build

**Comment by m-seldin** [comment]
approved for test build

**Comment by YafimK** [comment]
-[ ] Please verify the changes in shared modules with UFT stake holder.

**Comment by YafimK** [comment]
Approved for test build

**Comment by YafimK** [comment]
I will test it manually at most today's evening and merge.

**Comment by YafimK** [comment]
Approved for test build

**Pull request merged**
