### PR TITLE
fixing the exceptional cases in log dispatching flow

### PR DESCRIPTION
**Pull request by gullerya**
Please Make sure these boxes are checked before submitting your pull request - Thanks ahead!

- [x] Proper pull request title - concise and clear for others.
- [x] Proper pull request short description - clear and concise (as it should appear in the Jira ticket) for other developers and users.
- [x] Proper Jira ticket - Number, Link in pull request description.
- [x] The PR can is merged on your machine without any conflicts.
- [x] The PR can is built on your machine without any (new) warnings.
- [x] The PR passed sanity tests by you / QA / DevTest / Good Samaritain.
- [x] Add unit tests with new features.
- [x] If you added any dependency to the POM - Please update @YafimK

### CODE REVIEW

**Comment by gullerya** [comment]
In flows where logs should be sent to BDI analysis there could be some potential miss configuration leading to NumberFormatException, this issue is handled in this PR.

**Comment by YafimK** [comment]
@m-seldin please review

**Comment by YafimK** [comment]
@m-seldin : HI it seems that this fix was based on a branch before the re branding..
@gullerya I guess that a simple fix would be to update the branch and simply copy the most recent file over there - or fix those in their new location.

**Comment by YafimK** [comment]
Please update on current status on this PR. Can it be closed? @m-seldin

**Pull request closed without merging**
