### PR TITLE
UFT <-> Octane Integration bug fixes & support for a new BDI SDK

### PR DESCRIPTION
**Pull request by m-seldin**
- Error when creating pipeline from Jenkins for job inside folder (defect #368040)
- Delete UFT test in repository causes Jenkins discovery job to detect that internal data table is deleted (it should not be detected) (defect #363054)
- remove WARN Octane log messages from Jenkins system log
- fix string in getShortDescription of SuiteRunCase (octane-> ALM Octane)
- added support for a BDI client 2 with access token flavor

[JENKINS-45062](https://issues.jenkins-ci.org/browse/JENKINS-45062)
[JENKINS-45063](https://issues.jenkins-ci.org/browse/JENKINS-45063)
[JENKINS-45061](https://issues.jenkins-ci.org/browse/JENKINS-45061)
[JENKINS-45086](https://issues.jenkins-ci.org/browse/JENKINS-45086)

### CODE REVIEW

**Comment by m-seldin** [comment]
approved for test build

**Comment by m-seldin** [comment]
approved for test build

**Comment by YafimK** [comment]
1.  add JDocs.
2. I've noticed a different license - Apache 2 instead of our MIT.
    Requires further verification.

**Comment by m-seldin** [comment]
javadoc added

**Comment by YafimK** [comment]
approved for test build

**Pull request merged**
