### PR TITLE
Add variable resolver to fields and enable credential for Upload step

### PR DESCRIPTION
**Pull request by Roy-Lu**
1. Change username/password fields to credential in upload step.
2. Add variable resolver to test folder, test set folder, Jenkins URL fields.
3. Fix the alm server selection when initializing SSEbuilder page.

### CODE REVIEW

**Comment by Roy-Lu** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-44879

**Comment by Roy-Lu** [comment]
I don't understand the failure. Is the vm crashed?

**Comment by YafimK** [comment]
rerun the build due to system crash

**Comment by YafimK** [comment]
Hi,
please don't throw NPE's ... better to catch and treat them.
If it's discovered during run - and that's an error -> you should also catch it and fail the build.

**Comment by YafimK** [comment]
@Roy-Lu Thanks for fixing old issue!

**Comment by YafimK** [comment]
Approved for test build

**Pull request merged**
