### PR TITLE
Ocatne 5.2 beta-1 changes

### PR DESCRIPTION
**Pull request by m-seldin**
- log hidden exception

- promote mqm version to support base64 encoding in job name for multijob on secured envs
fixing PERFORMANCE_CENTER_RUNNER 
- Change the formet of test result
- defect #401115: Test results format - use test configuration for name
- Remove dependency of the plugin in BDI and make it send build logs to Octane instead of BDI (Jenkins plugin)

[JENKINS-45757](https://issues.jenkins-ci.org/browse/JENKINS-45757)
[JENKINS-45759](https://issues.jenkins-ci.org/browse/JENKINS-45759)
[JENKINS-46200](https://issues.jenkins-ci.org/browse/JENKINS-46200)

### CODE REVIEW

**Comment by YafimK** [comment]
Approved for test build

**Comment by YafimK** [comment]
Approved for test build

**Comment by radislavB** [comment]
@m-seldin Please add issue to  PR  https://issues.jenkins-ci.org/browse/JENKINS-46057

**Comment by m-seldin** [comment]
pull request transfered to the new repository
https://github.com/jenkinsci/hpe-application-automation-tools-plugin/pull/9

**Pull request closed without merging**
