### PR TITLE
fix for JENKINS-40758: Support run native browser mobile tests from Jenkins

### PR DESCRIPTION
**Pull request by jackzenko**
JENKINS-40758: Support run native browser mobile tests from Jenkins
related field in MC url is removed, thus users would be able to select browsers for testing.
https://issues.jenkins-ci.org/browse/JENKINS-40758

### CODE REVIEW

**Comment by YafimK** [comment]
Add link to jira issue

**Comment by YafimK** [comment]
test this PR

**Comment by YafimK** [comment]
test this PR

**Comment by YafimK** [comment]
test this PR

**Comment by jackzenko** [comment]
this is AGM user story, there is no link from JIRA.
it was tested by local QA.

**Comment by jackzenko** [comment]
Link added

**Pull request merged**
