### PR TITLE
Updated perform method to execute rest calls from slave node when slave node is available

### PR DESCRIPTION
**Pull request by coltrey**
Please review thoroughly before accepting - I don't think I broke any tests that weren't already broken in the development branch.
This implements https://issues.jenkins-ci.org/browse/JENKINS-28156

### CODE REVIEW

**Comment by bamh** [comment]
Hi Coltrey,

Could you please explain in more details what problem this implementation should solve?

Thanks,
Hanan.

**Comment by coltrey** [comment]
In order to support network zoning restrictions, this functionality will execute performance center rest calls on the build slave.  In some of our environments, for example, the jenkins Master exists in a zone isolated from the test environment for an application, and we then place the build slaves in those test areas - so instead of having firewalls open from master to test area, it's open from master to build slave and the build slave has permission to make the calls to performance center.

**Comment by bamh** [comment]
Hi,

Have you managed to run the test with a slave?

I get the following error on Jenkins:

Started by user anonymous<http://localhost:8080/jenkins/user/null>
Building remotely on myd-vm05959<http://localhost:8080/jenkins/computer/myd-vm05959> in workspace C:\Jenkins\workspace\aaa
FATAL: null
java.lang.NullPointerException<http://stacktrace.jenkins-ci.org/search?query=java.lang.NullPointerException>
        at com.hp.application.automation.tools.run.PcBuilder.perform(PcBuilder.java:141)<http://stacktrace.jenkins-ci.org/search/?query=com.hp.application.automation.tools.run.PcBuilder.perform&entity=method>
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)<http://stacktrace.jenkins-ci.org/search/?query=hudson.tasks.BuildStepMonitor$1.perform&entity=method>
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:780)<http://stacktrace.jenkins-ci.org/search/?query=hudson.model.AbstractBuild$AbstractBuildExecution.perform&entity=method>
        at hudson.model.Build$BuildExecution.build(Build.java:199)<http://stacktrace.jenkins-ci.org/search/?query=hudson.model.Build$BuildExecution.build&entity=method>
        at hudson.model.Build$BuildExecution.doRun(Build.java:160)<http://stacktrace.jenkins-ci.org/search/?query=hudson.model.Build$BuildExecution.doRun&entity=method>
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:565)<http://stacktrace.jenkins-ci.org/search/?query=hudson.model.AbstractBuild$AbstractBuildExecution.run&entity=method>
        at hudson.model.Run.execute(Run.java:1592)<http://stacktrace.jenkins-ci.org/search/?query=hudson.model.Run.execute&entity=method>
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<http://stacktrace.jenkins-ci.org/search/?query=hudson.model.FreeStyleBuild.run&entity=method>
        at hudson.model.ResourceController.execute(ResourceController.java:88)<http://stacktrace.jenkins-ci.org/search/?query=hudson.model.ResourceController.execute&entity=method>
            at hudson.model.Executor.run(Executor.java:237)<http://stacktrace.jenkins-ci.org/search/?query=hudson.model.Executor.run&entity=method>

When debugging I get an exception on class UserRequest.java from the remoting package:

    private byte[] serialize(Object o, Channel localChannel) throws IOException {
        try {
            return _serialize(o,localChannel);   // fails to serialize the channel
        } catch( NotSerializableException e ) {
            IOException x = new IOException("Unable to serialize " + o);
            x.initCause(e);
            throw x;
        }
    }


Please fix the code.

Thanks
Hanan.

**Comment by coltrey** [comment]
@bamh It's beyond my ability to debug this...I'm not a developer, I was just trying to help implement the functionality I need.

**Comment by bamh** [comment]
Hi,

We will try to find a way to implement this functionality through a configuration of Jenkins or using another plugin.
In case it won’t success this way, we will implement the functionality on our code in a future release.

I would like to thank you for suggesting this enhancement.
Best Regards,
Hanan.

**Comment by coltrey** [comment]
Thank you.

**Pull request closed without merging**
