### PR TITLE
fix discovery recursive  job calling

### PR DESCRIPTION
**Pull request by radislavB**
fix discovery recursive  job calling

### CODE REVIEW

**Comment by YafimK** [comment]
- Failed tests please review and fix either code or tests.
- Please add JavaDocs to changed files.
@m-seldin

**Comment by m-seldin** [comment]
@radislavB please see comments above.

**Review by YafimK — COMMENTED** [review]
- [ ] Please add JavaDoc to files

**Comment by m-seldin** [comment]
@YafimK reviewed. please merge.

**Comment by YafimK** [comment]
approved for test build

**Comment by m-seldin** [comment]
If jenkins job has triggering to itself - user is not able to create pipeline from Octane
(Inner defect 271070)
https://issues.jenkins-ci.org/browse/JENKINS-43688

**Pull request merged**
